### ISSUE TITLE
Improve the magbar labeling

### ISSUE THREAD

**Issue by Dailer** [asgr/magicaxis#10]
Hi Aaron! 
I am using the magicaxis package in nearly all mi figures, it is a great development. 

I have recently realized that the magbar labeling can be improved. For example, if I have a matrix (image) with a values within [-0.24,1.35], when plotting the colour bar, the values outside the 'range' values, which is displayed as blank (if clip='bg'), is too large. This can be solved or improved if the 'prettybase' of the maglab function can be set to 5 instead of 10 (default). So, I suggest to include the prettybase option in the magbar function, or create a function to automatically select the best base for a certain range.

Thanks!

**Comment by Dailer** [comment]
I have created a simple function that may help to solve this. The bases are reversed in order to get the minimum number of labels in case that there are two or more optimal bases.

```
prettybase = function(lim, bases = c(10, 9, 7, 5, 3, 2)){
  l = length(bases)
  dlim = diff(lim)
  p = vector(len = l)
  for (i in 1:l) {
    bi = bases[i]/10
    pt = pretty(lim/bi) * bi
    p[i] = diff(range(pt)) - dlim
  }
  return(bases[which.min(p)])
}
```

**Comment by asgr** [comment]
Glad to hear it's been useful for you.

I've gone for the simpler (for now) route of just passing to dots from magbar to maglab (since we have access to all the useful color.legend options already). You can use your helper function locally if it works for you, but it would be take me a while to check it produces the behaviour I'd want for a diversity of use cases.
