### ISSUE TITLE
Axis labels not displayed properly in log scale

### ISSUE THREAD

**Issue by Dailer** [asgr/magicaxis#8]
In some cases, the axis labels are not displayed properly in logarithmic scale, e.g.,
R> magplot(c(1.8, 4.3), c(0, 1), log='x')
here labels 3 and 4 are not displayed.
Is there a way to fix this?

**Comment by asgr** [comment]
Not really a bug, really a feature because of how high-level magplot is meant to be. It's because the dynamic range is way too small to make plotting it as logged valid- only a factor ~2. You shouldn't consider a log axis until the dynamic range is about 10.

If you really want to plot it like this you'll need to do something a bit more manual:

magplot(c(1.8, 4.3), c(0, 1), log='x', labels=c(F,T))
axis(1,2:4,2:4,tick=F)

**Comment by Dailer** [comment]
Thank you very much for replying!
